#!/usr/bin/env python3
"""
Regenerates supabase/catchup/ from the migrations.

The catch-up file was hand-concatenated the first time, and a hand-written
file that claims to be generated is a file that will quietly fall behind —
which for this one means a database missing a migration nobody notices until
a column doesn't exist.

Run it after adding a migration:

    python3 scripts/build-catchup.py

Then `--check` in CI, or by hand, to prove the file on disk still matches.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "supabase" / "migrations"
CATCHUP = ROOT / "supabase" / "catchup"

HEADER = """\
-- ============================================================================
-- CATCH-UP: migrations {first} through {last}, in order.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
--
-- Safe to run whatever state the database is in. Every statement from 0002
-- onwards is guarded (add column if not exists, create table if not exists,
-- drop policy if exists before create), so anything already applied is a
-- no-op rather than an error.
--
-- 0001_init.sql is deliberately NOT included: it creates tables outright and
-- would fail with "relation already exists". If your database has no tables
-- at all, run 0001 on its own first, then this.
--
-- GENERATED by scripts/build-catchup.py from supabase/migrations/.
-- Edit those files, then re-run the script. Do not edit this one.
-- ============================================================================
"""


def migration_files() -> list[Path]:
    files = sorted(p for p in MIGRATIONS.glob("*.sql") if re.match(r"\d{4}_", p.name))

    if not files:
        sys.exit("No migrations found.")

    # 0001 creates tables outright and can't be re-run.
    return [p for p in files if not p.name.startswith("0001_")]


def build() -> tuple[str, str]:
    files = migration_files()
    first, last = files[0].name[:4], files[-1].name[:4]

    parts = [HEADER.format(first=first, last=last)]

    for path in files:
        banner = f"  {path.name}  "
        parts.append(f"\n\n-- {'#' * 20}{banner}{'#' * 20}\n")
        parts.append(path.read_text().rstrip() + "\n")

    return f"{first}-{last}_catchup.sql", "".join(parts)


def main() -> int:
    name, content = build()
    target = CATCHUP / name
    check = "--check" in sys.argv

    # A renamed range leaves the old file behind, which would then be stale
    # and wrong rather than merely out of date.
    stale = [p for p in CATCHUP.glob("*_catchup.sql") if p.name != name]

    if check:
        if stale:
            print(f"FAIL  stale catch-up file(s): {', '.join(p.name for p in stale)}")
            return 1

        if not target.exists() or target.read_text() != content:
            print(f"FAIL  {target.relative_to(ROOT)} is out of date")
            print("      run: python3 scripts/build-catchup.py")
            return 1

        print(f"PASS  catch-up matches the {len(migration_files())} migrations it covers")
        return 0

    for path in stale:
        path.unlink()
        print(f"removed  {path.relative_to(ROOT)}")

    CATCHUP.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    print(f"wrote    {target.relative_to(ROOT)}  ({len(migration_files())} migrations)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
